#!/bin/bash

echo "IoT Monitoring System"
echo "===================="
echo ""
echo "Commands available:"
echo "  make build    - Build all containers"
echo "  make up       - Start all services"
echo "  make down     - Stop all services"
echo "  make logs     - View logs"
echo "  make restart  - Restart all services"
echo "  make status   - Show container status"
echo "  make clean    - Clean up containers and volumes"
echo ""
echo "Services will be available at:"
echo "  Frontend: http://localhost:3001"
echo "  Backend API: http://localhost:3000"
echo "  PostgreSQL: localhost:5432"
echo "  MQTT Broker: localhost:1883"
echo ""
